spring.application.name=ExamU2
spring.datasource.url=jdbc:mysql://localhost:3306/dbspring?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Cambia a create para que limpie y cargue el import.sql
spring.jpa.hibernate.ddl-auto=create
# Obliga a Spring a esperar que Hibernate cree las tablas antes de ejecutar el SQL
spring.jpa.defer-datasource-initialization=true
# Muestra el SQL en consola para ver si hay errores en el INSERT
spring.jpa.show-sql=true
